tasks:
  - name: Setup Rails App
    command: |
      if [ ! -d "./app" ]; then
      echo "Creating new Rails app with postgresql database..."
      docker-compose run --no-deps myrailsapp rails new . --force --database=postgresql
      echo "Changing ownership of the newly created files..."
      sudo chown -R $USER:$USER .
      echo "Rebuilding the Docker image..."
      docker-compose build
      docker-compose up